### ISSUE TITLE
ReferenceError: slackChannel is not defined

### ISSUE THREAD

**Issue by ianshward** [mapbox/dispatch#110]
> ReferenceError: slackChannel is not defined
at checkUser (/var/task/incoming/function.js:129:24)
at /var/task/incoming/function.js:49:20
at /var/task/lib/utils.js:13:7
at /var/task/node_modules/decrypt-kms-env/index.js:21:5
at Queue._call (/var/task/node_modules/decrypt-kms-env/index.js:67:5)
at maybeNotify (/var/task/node_modules/d3-queue/build/d3-queue.js:120:7)
at /var/task/node_modules/d3-queue/build/d3-queue.js:91:12
at Response.<anonymous> (/var/task/node_modules/decrypt-kms-env/index.js:61:9)
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:364:18)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)

It's as though something is going wrong in decrypt, or for some reason this lambda env var is not available or set to null, even though it is defined as a lambda env var.

**Comment by k-mahoney** [comment]
This has been (ideally) solved by #116 - going to close for now, will reopen if we have to track this error again.
